services:
  roomctl:
    build: .
    ports:
      - 9299:9199
    environment:
      APP_PORT: 9199
      APP_SWITCHBOT_TOKEN:      ${APP_SWITCHBOT_TOKEN}
      APP_SWITCHBOT_SECRET:     ${APP_SWITCHBOT_SECRET}
      APP_SWITCHBOT_DEVICEID:   ${APP_SWITCHBOT_DEVICEID}
      APP_SWITCHBOT_DEVICENAME: ${APP_SWITCHBOT_DEVICENAME}
