name: Publish Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          DOCKER_IMAGE=otknoy/mflight-api
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR=PR${{ github.event.number }}
            TAGS=${DOCKER_IMAGE}:${PR}-$(date +%Y%m%d-%H%M%M)
            TAGS=${TAGS},${DOCKER_IMAGE}:${PR}-$(date +%Y%m%d)
          elif [ "${{ github.event_name }}" = "push" ]; then
            TAGS=${DOCKER_IMAGE}:$(date +%Y%m%d-%H%M%M)
            TAGS=${TAGS},${DOCKER_IMAGE}:latest
          fi
          echo ::set-output name=tags::${TAGS}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prepare.outputs.tags }}
